"""modelo inicial

Revision ID: 8d9880ff76ea
Revises:
Create Date: 2026-08-22 20:26:26.847061

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d9880ff76ea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("slug", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("background", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_rooms")),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.String(length=12), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("avatar", sa.String(length=20), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column(
            "connected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.slug"],
            name=op.f("fk_participants_room_id_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participants")),
    )
    op.create_index(
        "ix_participants_room_active",
        "participants",
        ["room_id"],
        unique=False,
        postgresql_where="disconnected_at IS NULL",
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.String(length=12), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("own", "shared", name="note_kind"), nullable=False),
        sa.Column(
            "status", sa.Enum("blocked", "in_progress", "done", name="note_status"), nullable=False
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("position_x", sa.Float(), nullable=False),
        sa.Column("position_y", sa.Float(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("taken_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'own' AND capacity IS NULL) OR "
            "(kind = 'shared' AND capacity IS NOT NULL AND capacity > 0)",
            name=op.f("ck_notes_kind_capacity"),
        ),
        sa.CheckConstraint(
            "capacity IS NULL OR taken_count <= capacity",
            name=op.f("ck_notes_taken_count_le_capacity"),
        ),
        sa.CheckConstraint("char_length(text) <= 500", name=op.f("ck_notes_text_length")),
        sa.CheckConstraint("taken_count >= 0", name=op.f("ck_notes_taken_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["participants.id"],
            name=op.f("fk_notes_author_id_participants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["rooms.slug"], name=op.f("fk_notes_room_id_rooms"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notes")),
    )
    op.create_index(op.f("ix_notes_room_id"), "notes", ["room_id"], unique=False)
    op.create_index("ix_notes_room_id_status", "notes", ["room_id", "status"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.String(length=12), nullable=False),
        sa.Column("note_id", sa.UUID(), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(text) BETWEEN 1 AND 1000", name=op.f("ck_chat_messages_text_length")
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["participants.id"],
            name=op.f("fk_chat_messages_author_id_participants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.id"],
            name=op.f("fk_chat_messages_note_id_notes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.slug"],
            name=op.f("fk_chat_messages_room_id_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_messages")),
    )
    op.create_index(op.f("ix_chat_messages_note_id"), "chat_messages", ["note_id"], unique=False)
    op.create_index(
        "ix_chat_messages_room_created", "chat_messages", ["room_id", "created_at"], unique=False
    )
    op.create_table(
        "note_claims",
        sa.Column("note_id", sa.UUID(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column(
            "claimed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"], ["notes.id"], name=op.f("fk_note_claims_note_id_notes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_note_claims_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("note_id", "participant_id", name=op.f("pk_note_claims")),
    )
    op.create_table(
        "reactions",
        sa.Column("note_id", sa.UUID(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["note_id"], ["notes.id"], name=op.f("fk_reactions_note_id_notes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
            name=op.f("fk_reactions_participant_id_participants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("note_id", "participant_id", "emoji", name=op.f("pk_reactions")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reactions")
    op.drop_table("note_claims")
    op.drop_index("ix_chat_messages_room_created", table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_note_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_notes_room_id_status", table_name="notes")
    op.drop_index(op.f("ix_notes_room_id"), table_name="notes")
    op.drop_table("notes")
    # op.drop_table() no borra los tipos ENUM de Postgres: quedan huérfanos y la
    # siguiente 'upgrade head' falla con "type already exists" si no se limpian a mano.
    sa.Enum(name="note_kind").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="note_status").drop(op.get_bind(), checkfirst=False)
    op.drop_index(
        "ix_participants_room_active",
        table_name="participants",
        postgresql_where="disconnected_at IS NULL",
    )
    op.drop_table("participants")
    op.drop_table("rooms")
    # ### end Alembic commands ###
